server:
  port: 8080

spring:
  application:
    name: Masashi-Spring-boot-DEMO
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.84.20.93:3306/java_demo_3
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
